version: '3.8'  # Remove 'version' if using a recent Compose version to avoid warnings
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=crm_db

  mongodb:
    image: mongo:4.4.29
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=crm_db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  # Optional: set a username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123  # Optional: set a password
    depends_on:
      - mongodb

volumes:
  mongodb_data: